#!/usr/bin/env python3
"""
Fetch publication metadata from NASA ADS and regenerate
_data/publications.yml.

Reads links from pub_sources.yml (one per paper — an ADS abstract
URL, a bare bibcode, an arXiv URL/ID, or a DOI), looks each one up via
the ADS API, and writes _data/publications.yml with the parsed title,
authors, journal, and year. Authors are auto-bolded (wrapped in
<strong> tags) when they match an active entry in _data/roster.yml
for that paper's publication year.

SETUP (one-time):
  1. Get a free ADS API token: sign in at https://ui.adsabs.harvard.edu,
     then go to Account Settings -> API Token, and generate one.
  2. Set it as an environment variable before running:
       export ADS_API_TOKEN="your-token-here"
  3. Install dependencies:
       pip install requests pyyaml

USAGE:
  python3 scripts/fetch_publications.py            # fetch and write
  python3 scripts/fetch_publications.py --dry-run  # fetch, print only

This is meant to be run either locally before you push, or by the
"Update publications" GitHub Action (see .github/workflows/), which
runs it automatically and commits the result. Jekyll itself never
calls the network — this script is a separate step that produces a
plain data file Jekyll then reads normally.
"""

import os
import re
import sys
import unicodedata
import urllib.parse
import argparse

import requests
import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES_PATH = os.path.join(REPO_ROOT, "pub_sources.yml")
ROSTER_PATH = os.path.join(REPO_ROOT, "_data", "roster.yml")
OUTPUT_PATH = os.path.join(REPO_ROOT, "_data", "publications.yml")

ADS_API_URL = "https://api.adsabs.harvard.edu/v1/search/query"
MAX_AUTHORS_SHOWN = 10  # truncate long author lists to this many + "et al."

HEADER_COMMENT = """# AUTO-GENERATED by scripts/fetch_publications.py — do not hand-edit
# the entries below; they will be overwritten. To add a paper, add
# its link to pub_sources.yml and re-run the script instead. To
# change who gets bolded, edit _data/roster.yml.
#
# If you'd rather manage this file by hand instead of using the
# fetch script at all, that's fine too — just delete this header and
# edit entries directly; the site doesn't care how the file was
# produced, only that each entry has year/title/authors/venue/link/
# highlight.
"""


def parse_identifier(url):
    """Given a link, return an ADS search query fragment ('bibcode:...',
    'doi:...', or 'identifier:...') to look the paper up with."""
    url = url.strip()

    # Bare ADS bibcode (19 chars, e.g. 2026ApJ...123..456O)
    if re.fullmatch(r"[0-9]{4}[A-Za-z.&]{5}[0-9A-Za-z.]{4}[0-9A-Za-z.]{5}[A-Za-z]", url):
        return f'bibcode:"{url}"'

    # ADS abstract URL: bibcode sits between /abs/ and the next /
    m = re.search(r"/abs/([^/]+)/?", url)
    if m and "adsabs" in url:
        bibcode = urllib.parse.unquote(m.group(1))
        return f'bibcode:"{bibcode}"'

    # arXiv URL or bare arXiv ID (new-style: 4 digits, dot, 4-5 digits)
    m = re.search(r"arxiv\.org/abs/([\w.\-]+)", url, re.I)
    if m:
        return f'identifier:"arXiv:{m.group(1)}"'
    if re.fullmatch(r"\d{4}\.\d{4,5}(v\d+)?", url):
        return f'identifier:"arXiv:{url}"'

    # DOI, bare or as a doi.org URL
    m = re.search(r"doi\.org/(.+)", url, re.I)
    if m:
        return f'doi:"{urllib.parse.unquote(m.group(1))}"'
    if url.startswith("10."):
        return f'doi:"{url}"'

    return None


def fetch_record(query, token):
    """Query the ADS API for one paper and return the parsed fields,
    or None if nothing was found."""
    resp = requests.get(
        ADS_API_URL,
        params={
            "q": query,
            "fl": "bibcode,title,author,year,pub,doi",
            "rows": 1,
        },
        headers={"Authorization": f"Bearer {token}"},
        timeout=20,
    )
    resp.raise_for_status()
    docs = resp.json().get("response", {}).get("docs", [])
    if not docs:
        return None
    doc = docs[0]
    return {
        "bibcode": doc.get("bibcode", ""),
        "title": (doc.get("title") or [""])[0],
        "authors": doc.get("author", []),
        "year": int(doc["year"]) if doc.get("year") else None,
        "venue": doc.get("pub", ""),
    }


def load_roster():
    if not os.path.exists(ROSTER_PATH):
        return []
    with open(ROSTER_PATH) as f:
        return yaml.safe_load(f) or []


def strip_accents(s):
    """Normalize accented characters so 'Tomás' and 'Tomas' compare
    equal — ADS records aren't always consistent about diacritics,
    and neither are the names people type into roster.yml by hand."""
    return "".join(
        c for c in unicodedata.normalize("NFKD", s)
        if not unicodedata.combining(c)
    )


def normalize(s):
    return strip_accents(s).lower().strip()


def parse_author(raw):
    """ADS author strings are usually 'Last, First Middle'. Split on
    the first comma to get (last, first_rest). If there's no comma
    (rare — collaboration names, or unusually formatted entries),
    fall back to treating the last whitespace-separated token as the
    surname."""
    raw = raw.strip()
    if "," in raw:
        last, rest = raw.split(",", 1)
        return last.strip(), rest.strip()
    parts = raw.split()
    if len(parts) >= 2:
        return parts[-1], " ".join(parts[:-1])
    return raw, ""


def display_name(raw):
    """Convert 'Last, First Middle' to 'First Middle Last' reading
    order for display on the site."""
    last, first_rest = parse_author(raw)
    if not first_rest:
        return last  # collaboration name or single token — leave as-is
    return f"{first_rest} {last}"


def is_group_member(raw_author, year, roster):
    last, first_rest = parse_author(raw_author)
    last_n = normalize(last)
    # first initial only — strips any trailing period/whitespace so
    # "T." and "T" and "Tomás" all reduce to the same leading letter(s)
    first_n = normalize(first_rest)

    for entry in roster:
        entry_last = normalize(entry.get("last", ""))
        entry_initial = normalize(re.sub(r"[.\s]", "", entry.get("first_initial", "")))
        if not entry_last or not entry_initial:
            continue
        if last_n != entry_last:
            continue
        if not first_n.startswith(entry_initial):
            continue
        start = entry.get("start_year")
        end = entry.get("end_year")
        if start is not None and year is not None and year < start:
            continue
        if end is not None and year is not None and year > end:
            continue
        return True
    return False


def format_authors(authors, year, roster):
    """Join author names in 'First Last' reading order, bolding group
    members, truncating long lists but always keeping any group
    member visible even if truncated."""
    marked = [(a, is_group_member(a, year, roster)) for a in authors]

    if len(marked) <= MAX_AUTHORS_SHOWN:
        shown = marked
        overflow_members = []
    else:
        shown = marked[:MAX_AUTHORS_SHOWN]
        overflow_members = [a for a, is_gm in marked[MAX_AUTHORS_SHOWN:] if is_gm]

    parts = [
        f"<strong>{display_name(a)}</strong>" if is_gm else display_name(a)
        for a, is_gm in shown
    ]
    if len(marked) > MAX_AUTHORS_SHOWN:
        if overflow_members:
            extra = ", ".join(f"<strong>{display_name(a)}</strong>" for a in overflow_members)
            parts.append(f"et al. (incl. {extra})")
        else:
            parts.append("et al.")

    return ", ".join(parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="fetch and print, don't write the file")
    args = parser.parse_args()

    token = os.environ.get("ADS_API_TOKEN")
    if not token:
        print("ERROR: set the ADS_API_TOKEN environment variable first.", file=sys.stderr)
        print("Get a free token at https://ui.adsabs.harvard.edu/user/settings/token", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(SOURCES_PATH):
        print(f"ERROR: {SOURCES_PATH} not found.", file=sys.stderr)
        sys.exit(1)

    with open(SOURCES_PATH) as f:
        sources = yaml.safe_load(f) or []

    roster = load_roster()
    results = []

    for i, source in enumerate(sources, 1):
        url = source.get("url", "").strip()
        if not url:
            continue
        query = parse_identifier(url)
        if not query:
            print(f"[{i}] SKIPPED — couldn't recognize link type: {url}", file=sys.stderr)
            continue

        print(f"[{i}] Looking up {url} ...")
        try:
            record = fetch_record(query, token)
        except requests.HTTPError as e:
            print(f"[{i}] ERROR — ADS request failed: {e}", file=sys.stderr)
            continue
        except requests.RequestException as e:
            print(f"[{i}] ERROR — network error: {e}", file=sys.stderr)
            continue

        if not record or not record["authors"]:
            print(f"[{i}] WARNING — no record found for: {url}", file=sys.stderr)
            continue

        authors_html = format_authors(record["authors"], record["year"], roster)
        first_author_is_group = is_group_member(record["authors"][0], record["year"], roster)

        entry = {
            "year": record["year"],
            "title": record["title"],
            "authors": authors_html,
            "venue": record["venue"],
            "link": source.get("link") or f"https://ui.adsabs.harvard.edu/abs/{record['bibcode']}/abstract",
            "highlight": source.get("highlight", first_author_is_group),
        }
        results.append(entry)
        print(f"    -> {entry['title']!r} ({entry['year']})")

    results.sort(key=lambda e: e["year"] or 0, reverse=True)

    if args.dry_run:
        print("\n--- dry run: would write ---\n")
        print(yaml.safe_dump(results, sort_keys=False, allow_unicode=True))
        return

    with open(OUTPUT_PATH, "w") as f:
        f.write(HEADER_COMMENT)
        f.write("\n")
        yaml.safe_dump(results, f, sort_keys=False, allow_unicode=True, width=1000)

    print(f"\nWrote {len(results)} publication(s) to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
